version: '3'

services:

  postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_Role: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gin-gonic-api
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
